#    Copyright 2023 The ChampSim Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import difflib
import hashlib
import itertools
import operator
import os
import json
import pathlib

from . import modules
from .makefile import get_discovery_makefile_lines
from .module_registry import registry_class_lines
from .module_registry import registry_impl_lines
from . import util

warning_text = (
'THIS FILE IS AUTOMATICALLY GENERATED',
'Do not edit this file. It will be overwritten when the configure script is run.',
)

def contextualize_warning(prefix, line_prefix, suffix):
    ''' Generate a warning contextualized with the given comment aspects. '''
    return (prefix, *(f' {line_prefix} {l}' for l in warning_text), suffix, '')

def cxx_generated_warning():
    ''' Generate a warning commented in a C++ style. '''
    return contextualize_warning('/***', '*', '***/')

def make_generated_warning():
    ''' Generate a warning commented in a Make style. '''
    return contextualize_warning('###', '#', '###')

def cxx_file(lines):
    ''' Generate a C++ file, with a warning header. '''
    yield from cxx_generated_warning()
    yield from lines

def files_are_different(rfp, new_rfp, verbose=False):
    ''' Determine if the two files are different, excluding whitespace at the beginning or end of lines '''
    old_file_lines = list(l.strip() for l in rfp)
    new_file_lines = list(l.strip() for l in new_rfp)
    diff = difflib.SequenceMatcher(a=old_file_lines, b=new_file_lines).ratio()
    if verbose:
        print('File difference:', diff)
    return diff < 1

def write_if_different(fname, new_file_string, file=None, verbose=False):
    '''
    Write to a file if and only if it differs from an existing file with the same name.

    :param fname: the name of the destination file
    :param new_file_string: the desired contents of the file
    '''
    should_write = True
    if os.path.exists(fname):
        with open(fname, 'rt') as rfp:
            should_write = files_are_different(rfp, new_file_string.splitlines())

    if should_write:
        if verbose:
            print("Writing file", fname)

        if file is None:
            os.makedirs(os.path.abspath(os.path.dirname(fname)), exist_ok=True)
            with open(fname, 'wt') as wfp:
                wfp.write(new_file_string)
        else:
            file.write(new_file_string)

def try_int(val):
    '''
    Attempt to convert the value to a Python standard int.
    For use with json.dump().
    '''
    try:
        return int(val)
    except Exception as exc:
        raise TypeError from exc

class Fragment:
    '''
    Examines the given config and prepares to write the needed files.

    Programs may use this class for fine-grained control of when and how files are written.
    '''
    @staticmethod
    def __part_joiner(iterable):
        it = iter(iterable)
        key, first_value = next(it)

        header_len = 0
        if os.path.splitext(key)[1] in ('.cc', '.h', '.inc'):
            header_len = len(cxx_generated_warning())
        if os.path.splitext(key)[1] in ('.mk',):
            header_len = len(make_generated_warning())

        contents_parts = (itertools.islice(v[1], header_len, None) for v in it)
        return key, tuple(itertools.chain(first_value, *contents_parts))

    def __init__(self, fileparts=None):
        self.fileparts = list(fileparts or [])

    @staticmethod
    def join(*frags):
        ''' Merge multiple Fragments into one. '''
        joined_parts = list(itertools.chain(*(f.file_parts() for f in frags)))
        fileparts = list(util.collect(joined_parts, operator.itemgetter(0), Fragment.__part_joiner))
        return Fragment(fileparts)

    def write(self, verbose=False):
        ''' Write the internal series of fragments to file. '''
        for fname, fcontents in self.fileparts:
            write_if_different(fname, '\n'.join(l.rstrip() for l in fcontents), verbose=verbose)

    def file_parts(self):
        return self.fileparts

    def __iter__(self):
        return iter(self.file_parts())

def write_discovery(executable_name, bindir_name, objdir_name, makedir_name, module_dir=None, branch_dir=None,
                    btb_dir=None, pref_dir=None, repl_dir=None, verbose=False):
    """
    Emit everything that still has to be generated: the module registry and the
    makefile fragment naming the module objects.

    The simulated machine is written in C++ and configured at run time, so
    nothing here describes a machine. What a header cannot know is which
    modules exist on disk -- that is what this discovers.
    """
    objdir_name = os.path.abspath(objdir_name)
    module_info = modules.get_module_info(module_dir=module_dir, branch_dir=branch_dir, btb_dir=btb_dir,
                                          pref_dir=pref_dir, repl_dir=repl_dir, verbose=verbose)

    joined = util.chain(*module_info.values())
    executable = os.path.join(bindir_name, executable_name)

    Fragment([
        (os.path.join(objdir_name, 'registry.inc'), cxx_file(registry_class_lines(module_info))),
        (os.path.join(objdir_name, 'registry.cc.inc'), cxx_file(registry_impl_lines(module_info))),
        (os.path.join(makedir_name or '.', '_configuration.mk'), (
            *make_generated_warning(),
            *get_discovery_makefile_lines(executable, joined)
        ))
    ]).write(verbose=verbose)
